# This workflow runs on `pull_request`.
#
# `Lint code base` job uses `checkout` to download the content of the repository. It uses GitHub Action
# `super-linter/super-linter` to run a combination of various linters, written in bash, to help validate
# your source code.
#
# Documentation
# - https://github.com/marketplace/actions/super-linter

name: Lint Code Base

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - '*'                      # matches every branch that doesn't contain a '/'
      - '*/*'                    # matches every branch containing a single '/'
      - '**'                     # matches every branch

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  build:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          # Need to define main branch as default
          # is set to master in super-linter
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The following linter types will be enabled:
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_POWERSHELL: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_YAML: true
          # Additional settings:
          # If a shell script is not executable, the bash-exec
          # linter will report an error when set to true
          ERROR_ON_MISSING_EXEC_BIT: true
          # Exclude README.md file because it is generated
          FILTER_REGEX_EXCLUDE: README.md
