formatter: markdown document  # this is required

version: 0.16.0

header-from: docs/README_header.md
footer-from: docs/README_footer.md

recursive:
  enabled: false

sections:
  hide: []
  show: []

  hide-all: false  # deprecated in v0.13.0, removed in v0.15.0
  show-all: true   # deprecated in v0.13.0, removed in v0.15.0

content: |-
  {{ .Header }}

  ## Documentation

  {{ .Requirements }}

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Resources }}

  {{ .Outputs }}

  <!-- markdownlint-enable -->
  {{ .Footer }}

output:
  file: README.md
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
